name: Prowler Continuous Compliance Audit

on:
  schedule:
    # This cron job runs the audit automatically every midnight
    - cron: '0 0 * * *' 
  workflow_dispatch: 
    # This magic line gives you a manual "Run Workflow" button in GitHub for your demo!

jobs:
  prowler-audit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Change this if your resources are in a different region

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Prowler
        run: pip install prowler

      - name: Execute Prowler CIS Benchmark
        # We tell Prowler to output both a CSV (for data parsing) and an HTML file (for a pretty dashboard)
        run: prowler aws --compliance cis_2.0_aws -M csv html
        continue-on-error: true
      - name: Upload Compliance Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: prowler-compliance-reports
          path: output/